apiVersion: v1
kind: Service
metadata:
  name: departamento
  labels:
    app: departamento
spec:
  selector:
    app: departamento
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: departamento-deployment
spec:
  selector:
    matchLabels:
      app: departamento
  template:
    metadata:
      labels:
        app: departamento
    spec:
      containers:
        - name: departamento
          image: "707413322123.dkr.ecr.sa-east-1.amazonaws.com/cisp-departamento"
          ports:
          - containerPort: 8083
          env:
          - name: MYSQL_HOST
            value: "cisp-rds-mariadb.cstlzoc1hdwc.sa-east-1.rds.amazonaws.com"
          - name: MYSQL_TCP_PORT
            value: "3306"
          - name: MYSQL_PWD
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: password
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          livenessProbe:
            httpGet:
              path: "/"
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            exec:      
              command:
              - cat
              - /log/departamento.log
            initialDelaySeconds: 20
            periodSeconds: 3

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: departamento-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: departamento-deployment
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

