apiVersion: v1
kind: Service
metadata:
  name: segmento
  labels:
    app: segmento
spec:
  selector:
    app: segmento
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmento-deployment
spec:
  selector:
    matchLabels:
      app: segmento
  template:
    metadata:
      labels:
        app: segmento
    spec:
      containers:
        - name: segmento
          image: "707413322123.dkr.ecr.sa-east-1.amazonaws.com/cisp-segmento:latest"  
          ports:
          - containerPort: 8081
          env:
          - name: MYSQL_HOST
            value: "cisp-rds-mariadb.cstlzoc1hdwc.sa-east-1.rds.amazonaws.com"
          - name: MYSQL_TCP_PORT
            value: "3306"
          - name: MYSQL_PWD
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: password
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          livenessProbe:
            httpGet:
              path: "/"
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            exec:      
              command:
              - cat
              - /log/segmento.log
            initialDelaySeconds: 20
            periodSeconds: 3

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: segmento-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: segmento-deployment
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

